package com.pourbaix.infinity.domain;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Immutable;

/**
 * OpcodeParameter generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "OPCODE_PARAMETER", schema = "PUBLIC", catalog = "PUBLIC")
@Cacheable
@Cache(usage = CacheConcurrencyStrategy.READ_ONLY)
public class OpcodeParameter implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	private int id;

	@Column(name = "NAME", nullable = false, length = 50)
	private String name;

	@Column(name = "IDS", length = 8)
	private String ids;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parameter")
	@Immutable
	private Set<OpcodeParameterLink> parameters = new HashSet<OpcodeParameterLink>(0);

	@Cache(usage = CacheConcurrencyStrategy.READ_ONLY)
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parameter")
	@Immutable
	private Set<OpcodeParameterValue> values = new HashSet<OpcodeParameterValue>(0);

	public OpcodeParameter() {
	}

	public OpcodeParameter(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public OpcodeParameter(int id, String name, String ids, Set<OpcodeParameterLink> parameters, Set<OpcodeParameterValue> values) {
		this.id = id;
		this.name = name;
		this.ids = ids;
		this.parameters = parameters;
		this.values = values;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIds() {
		return this.ids;
	}

	public void setIds(String ids) {
		this.ids = ids;
	}

	public Set<OpcodeParameterLink> getParameters() {
		return this.parameters;
	}

	public void setParameters(Set<OpcodeParameterLink> parameters) {
		this.parameters = parameters;
	}

	public Set<OpcodeParameterValue> getValues() {
		return this.values;
	}

	public void setValues(Set<OpcodeParameterValue> values) {
		this.values = values;
	}

}
