package old;
public enum StateEnum {
	STATE_HARMLESS, STATE_CONFUSED, STATE_PANIC, STATE_NOT_VISIBLE, STATE_SILENCED, STATE_CHARMED, STATE_POISONED, 
	STATE_DRAWUPONHOLYMIGHT, STATE_HASTED, STATE_ENCHANTED, STATE_ILLUSIONS, STATE_BLUR, STATE_BLESS, STATE_MIRRORIMAGE, 
	STATE_STUNNED, STATE_INVISIBLE, STATE_SLEEPING, STATE_SLOWED, STATE_BLIND, STATE_FEEBLEMINDED, STATE_IMPROVEDINVISIBILITY, 
	STATE_DISABLED, STATE_REALLY_DEAD, STATE_OUT_OF_ACTION
}
