package old;
public enum StatEnum {
	HELD, TURNUNDEADLEVEL, SPELLFAILUREMAGE, SPELLFAILUREPRIEST, SANCTUARY,
	PROTECTION_FROM_EVIL, LEVEL, MAGICDAMAGERESISTANCE, AURACLEANSING,   
	SCRIPTINGSTATE1, SCRIPTINGSTATE2, SCRIPTINGSTATE3, SCRIPTINGSTATE4, SCRIPTINGSTATE5, SCRIPTINGSTATE6,
	STR, STONESKINS, ENTANGLE, RESISTFIRE, RESISTMAGICFIRE, RESISTCOLD, RESISTMAGICCOLD, RESISTELECTRICITY, RESISTPOISON, RESISTACID, RESISTMAGIC,
	WIZARD_TENSERS_TRANSFORMATION, WIZARD_PROTECTION_FROM_MAGIC_WEAPONS, WIZARD_PROTECTION_FROM_NORMAL_WEAPONS, CLERIC_SHIELD_OF_THE_ARCHONS, WIZARD_SPELL_TRAP, WIZARD_SPELL_TURNING,
	WIZARD_SPELL_DEFLECTION, GLOBE_OF_INVULNERABILITY, SHAPECHANGE, POLYMORPH_SELF, POLYMORPH_OTHER, 
	CLERIC_FREE_ACTION, WIZARD_GREATER_MALISON, SHAPESHIFT, WIZARD_SPELL_IMMUNITY
}
