package com.pourbaix.script.creature.model;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Keyword generated by hbm2java
 */
@Entity
@Table(name="KEYWORD"
    ,schema="PUBLIC"
    ,catalog="PUBLIC"
    , uniqueConstraints = @UniqueConstraint(columnNames="NAME") 
)
public class Keyword  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String type;
     private Set<TriggerKeyword> triggerKeywords = new HashSet<TriggerKeyword>(0);

    public Keyword() {
    }

	
    public Keyword(String name, String type) {
        this.name = name;
        this.type = type;
    }
    public Keyword(String name, String type, Set<TriggerKeyword> triggerKeywords) {
       this.name = name;
       this.type = type;
       this.triggerKeywords = triggerKeywords;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set<TriggerKeyword> getTriggerKeywords() {
        return this.triggerKeywords;
    }
    
    public void setTriggerKeywords(Set<TriggerKeyword> triggerKeywords) {
        this.triggerKeywords = triggerKeywords;
    }




}


