package com.pourbaix.script.creature.trigger;

import com.pourbaix.script.creature.generator.GeneratorException;

public enum ShortcutEnum {
	STATE_DISABLED, STATE_OUT_OF_ACTION, STATE_STUNNED, STATE_PANIC, STATE_CONFUSED, STATE_CHARMED, STATE_SLOWED, STATE_HASTED, STATE_BLIND, STATE_MIRRORIMAGE, STATE_HARMLESS, STATE_POISONED, STATE_SILENCED, STATE_SLEEPING, STATE_IMPROVEDINVISIBILITY, STATE_INVISIBLE, HOLD, SANCTUARY, PROTECTION_WEAPON, PROTECTION_MAGIC_WEAPON, PROTECTION_SPELL, FREE_ACTION, GREATER_MALISON, PROTECTION_FROM_EVIL, STONESKIN, SPELL_FAILURE, IMMUNITY_POISON, IMMUNITY_FIRE, IMMUNITY_COLD, IMMUNITY_ELECTRICITY, IMMUNITY_ACID, IMMUNITY_MAGIC_DAMAGE, IMMUNITY_MAGIC, MINORGLOBE, GLOBE, MAJORGLOBE, IMMUNITY_INVOCATION, IMMUNITY_CONJURATION, IMMUNITY_DIVINATION, IMMUNITY_ENCHANTMENT, IMMUNITY_NECROMANCY, IMMUNITY_ALTERATION, SHIELD, RAGE, KAI, OUTDOOR, RANDOM_100, RANDOM_1000, HIT_POINT_50, HIT_POINT_25, HIT_POINT_10, DETECT_ENEMY, SEE_ENEMY, SEE_NEAREST, MAGICAL_WEAPON_ITEM, VALID, ATTACKED, HIT, RANGE_HIT, IMMUNITY_WEAPON, CAN_CAST, PLAYER_RANGE, AREA_OF_EFFECT, VISIBLE, ELF, MONK, CASTER, FIGHTER, INQUISITOR, ANIMAL, UNDEAD, SUMMON, MIST, IMMUNITY_SLEEP, IMMUNITY_HOLD, IMMUNITY_CHARM, IMMUNITY_STUN, IMMUNITY_DEATH, IMMUNITY_FEAR, IMMUNITY_CONFUSION, ENCHANTED, ILLUSION, HAVE_SPELL, NO_RANDOM, NO_MEM, NO_ROUND, NO_DISABLE_CHECK, ROUND;

	public static ShortcutEnum fromString(final String text) throws GeneratorException {
		if (text != null) {
			for (ShortcutEnum value : ShortcutEnum.values()) {
				if (text.trim().equalsIgnoreCase(value.toString())) {
					return value;
				}
			}
		}
		throw new GeneratorException("Unknown shortcut trigger: " + text);
	}
}
