/*
 * Created on 16 nov. 2013 ( Time 09:59:22 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package com.pourbaix.script.creature.dao;


import com.pourbaix.script.creature.model.Trigger ;

public interface TriggerDao extends AbstractDao<Trigger, String> {
    
}
