/*
 * Created on 16 nov. 2013 ( Time 10:25:37 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package com.pourbaix.script.creature.dao;


import com.pourbaix.script.creature.model.TriggerKeyword ;

public interface TriggerKeywordDao extends AbstractDao<TriggerKeyword, Integer> {
    
}
