/*
 * Created on 16 nov. 2013 ( Time 09:59:22 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package com.pourbaix.script.creature.dao.impl;


import com.pourbaix.script.creature.model.Keyword ;
import com.pourbaix.script.creature.dao.KeywordDao;

import org.springframework.stereotype.Repository;

/**
 * JPA implementation for basic persistence operations ( entity "Keyword" )
 * 
 * @author Telosys Tools Generator
 *
 */
@Repository
public class KeywordDaoImpl extends AbstractDaoImpl<Keyword, Integer> implements KeywordDao {

    protected KeywordDaoImpl() {
        super(Keyword.class);
    }
    
}
