/*
 * Created on 16 nov. 2013 ( Time 10:25:37 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package com.pourbaix.script.creature.dao.impl;


import com.pourbaix.script.creature.model.TriggerKeyword ;
import com.pourbaix.script.creature.dao.TriggerKeywordDao;

import org.springframework.stereotype.Repository;

/**
 * JPA implementation for basic persistence operations ( entity "TriggerKeyword" )
 * 
 * @author Telosys Tools Generator
 *
 */
@Repository
public class TriggerKeywordDaoImpl extends AbstractDaoImpl<TriggerKeyword, Integer> implements TriggerKeywordDao {

    protected TriggerKeywordDaoImpl() {
        super(TriggerKeyword.class);
    }
    
}
