package com.pourbaix.creature.editor.domain;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TriggerKeyword generated by hbm2java
 */
@Entity
@Table(name = "ACTION_KEYWORD", schema = "PUBLIC", catalog = "PUBLIC")
public class ActionKeyword implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private Integer id;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "KEYWORD_ID")
	private Keyword keyword;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ACTION_ID")
	private Action action;

	@Column(name = "PARAM1", length = 50)
	private String param1;

	@Column(name = "PARAM2", length = 50)
	private String param2;

	@Column(name = "PARAM3", length = 50)
	private String param3;

	@Column(name = "PARAM4", length = 50)
	private String param4;

	public ActionKeyword() {
	}

	public ActionKeyword(Keyword keyword, Action action, String param1, String param2, String param3, String param4) {
		this.keyword = keyword;
		this.action = action;
		this.param1 = param1;
		this.param2 = param2;
		this.param3 = param3;
		this.param4 = param4;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Keyword getKeyword() {
		return this.keyword;
	}

	public void setKeyword(Keyword keyword) {
		this.keyword = keyword;
	}

	public Action getAction() {
		return action;
	}

	public void setAction(Action action) {
		this.action = action;
	}

	public String getParam1() {
		return this.param1;
	}

	public void setParam1(String param1) {
		this.param1 = param1;
	}

	public String getParam2() {
		return this.param2;
	}

	public void setParam2(String param2) {
		this.param2 = param2;
	}

	public String getParam3() {
		return this.param3;
	}

	public void setParam3(String param3) {
		this.param3 = param3;
	}

	public String getParam4() {
		return this.param4;
	}

	public void setParam4(String param4) {
		this.param4 = param4;
	}

}
