package com.pourbaix.creature.editor.domain;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Attribute generated by hbm2java
 */
@Entity
@Table(name = "ATTRIBUTE", schema = "PUBLIC", catalog = "PUBLIC")
@Cacheable
@Cache(usage = CacheConcurrencyStrategy.READ_ONLY)
public class Attribute implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 30)
	@Enumerated(EnumType.STRING)
	private AttributeEnum id;

	@Column(name = "SHORT_LABEL", length = 100)
	private String shortLabel;

	@Column(name = "LONG_LABEL", length = 250)
	private String longLabel;

	@Column(name = "TYPE", length = 20)
	@Enumerated(EnumType.STRING)
	private AttributeTypeEnum type;

	@Column(name = "MIN_VALUE")
	private Integer minValue;

	@Column(name = "MAX_VALUE")
	private Integer maxValue;

	@Column(name = "LENGTH")
	private Integer length;

	public AttributeEnum getId() {
		return id;
	}

	public void setId(AttributeEnum id) {
		this.id = id;
	}

	public String getShortLabel() {
		return this.shortLabel;
	}

	public void setShortLabel(String shortLabel) {
		this.shortLabel = shortLabel;
	}

	public String getLongLabel() {
		return this.longLabel;
	}

	public void setLongLabel(String longLabel) {
		this.longLabel = longLabel;
	}

	public AttributeTypeEnum getType() {
		return this.type;
	}

	public void setType(AttributeTypeEnum type) {
		this.type = type;
	}

	public Integer getMinValue() {
		return this.minValue;
	}

	public void setMinValue(Integer minValue) {
		this.minValue = minValue;
	}

	public Integer getMaxValue() {
		return this.maxValue;
	}

	public void setMaxValue(Integer maxValue) {
		this.maxValue = maxValue;
	}

	public Integer getLength() {
		return this.length;
	}

	public void setLength(Integer length) {
		this.length = length;
	}

}
