package com.pourbaix.creature.editor.domain;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Attribute generated by hbm2java
 */
@Entity
@Table(name = "ATTRIBUTE", schema = "PUBLIC", catalog = "PUBLIC")
public class Attribute implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private Integer id;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ATTRIBUTE_ID")
	private Attribute parent;

	@Column(name = "NAME", nullable = false, length = 30)
	private String name;

	@Column(name = "SHORT_LABEL", length = 100)
	private String shortLabel;

	@Column(name = "LONG_LABEL", length = 250)
	private String longLabel;

	@Column(name = "TYPE", length = 20)
	private String type;

	@Column(name = "MIN_VALUE")
	private Integer minValue;

	@Column(name = "MAX_VALUE")
	private Integer maxValue;

	@Column(name = "LENGTH")
	private Integer length;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parent")
	private Set<Attribute> children = new HashSet<Attribute>(0);

	public Attribute() {
	}

	public Attribute(String name) {
		this.name = name;
	}

	public Attribute(Attribute parent, String name, String shortLabel, String longLabel, String type, Integer minValue, Integer maxValue, Integer length,
			Set<Attribute> children) {
		this.parent = parent;
		this.name = name;
		this.shortLabel = shortLabel;
		this.longLabel = longLabel;
		this.type = type;
		this.minValue = minValue;
		this.maxValue = maxValue;
		this.length = length;
		this.children = children;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Attribute getParent() {
		return this.parent;
	}

	public void setParent(Attribute parent) {
		this.parent = parent;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getShortLabel() {
		return this.shortLabel;
	}

	public void setShortLabel(String shortLabel) {
		this.shortLabel = shortLabel;
	}

	public String getLongLabel() {
		return this.longLabel;
	}

	public void setLongLabel(String longLabel) {
		this.longLabel = longLabel;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Integer getMinValue() {
		return this.minValue;
	}

	public void setMinValue(Integer minValue) {
		this.minValue = minValue;
	}

	public Integer getMaxValue() {
		return this.maxValue;
	}

	public void setMaxValue(Integer maxValue) {
		this.maxValue = maxValue;
	}

	public Integer getLength() {
		return this.length;
	}

	public void setLength(Integer length) {
		this.length = length;
	}

	public Set<Attribute> getChildren() {
		return this.children;
	}

	public void setChildren(Set<Attribute> children) {
		this.children = children;
	}

}
