package com.pourbaix.creature.editor.domain;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Game generated by hbm2java
 */
@Entity
@Table(name = "GAME", schema = "PUBLIC", catalog = "PUBLIC")
public class Game implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private Integer id;

	@Column(name = "NAME", nullable = false, length = 50)
	private String name;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "game")
	private Set<Creature> creatures = new HashSet<Creature>(0);

	public Game() {
	}

	public Game(String name) {
		this.name = name;
	}

	public Game(String name, Set<Creature> creatures) {
		this.name = name;
		this.creatures = creatures;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Creature> getCreatures() {
		return this.creatures;
	}

	public void setCreatures(Set<Creature> creatures) {
		this.creatures = creatures;
	}

}
