package com.pourbaix.creature.editor.domain;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * GameEdition generated by hbm2java
 */
@Entity
@Table(name = "GAME_EDITION", schema = "PUBLIC", catalog = "PUBLIC")
@Cacheable
@Cache(usage = CacheConcurrencyStrategy.READ_ONLY)
public class GameEdition implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	@Enumerated(EnumType.STRING)
	private GameEditionEnum id;

	@Column(name = "NAME", nullable = false, length = 50)
	private String name;

	public GameEditionEnum getId() {
		return id;
	}

	public void setId(GameEditionEnum id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
