package com.pourbaix.creature.editor.domain;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedAttributeNode;
import javax.persistence.NamedEntityGraph;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Keyword generated by hbm2java
 */
@Entity
@Table(name = "KEYWORD", schema = "PUBLIC", catalog = "PUBLIC", uniqueConstraints = @UniqueConstraint(columnNames = "NAME"))
@NamedEntityGraph(name = "Keyword.lists", attributeNodes = @NamedAttributeNode("actionKeywords"))
public class Keyword implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private Integer id;

	@Column(name = "NAME", unique = true, nullable = false, length = 50)
	private String name;

	@Column(name = "TYPE", nullable = false, length = 15)
	@Enumerated(EnumType.STRING)
	private KeywordTypeEnum type;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "keyword")
	private Set<TriggerKeyword> triggerKeywords = new HashSet<TriggerKeyword>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "keyword")
	private Set<ActionKeyword> actionKeywords = new HashSet<ActionKeyword>(0);

	public Keyword() {
	}

	public Keyword(String name, KeywordTypeEnum type) {
		this.name = name;
		this.type = type;
	}

	public Keyword(String name, KeywordTypeEnum type, Set<TriggerKeyword> triggerKeywords) {
		this.name = name;
		this.type = type;
		this.triggerKeywords = triggerKeywords;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public KeywordTypeEnum getType() {
		return this.type;
	}

	public void setType(KeywordTypeEnum type) {
		this.type = type;
	}

	public Set<TriggerKeyword> getTriggerKeywords() {
		return this.triggerKeywords;
	}

	public void setTriggerKeywords(Set<TriggerKeyword> triggerKeywords) {
		this.triggerKeywords = triggerKeywords;
	}

	public Set<ActionKeyword> getActionKeywords() {
		return actionKeywords;
	}

	public void setActionKeywords(Set<ActionKeyword> actionKeywords) {
		this.actionKeywords = actionKeywords;
	}

}
