package com.pourbaix.creature.editor.domain;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Immutable;

/**
 * Opcode generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "OPCODE", schema = "PUBLIC", catalog = "PUBLIC")
@Cacheable
@Cache(usage = CacheConcurrencyStrategy.READ_ONLY)
public class Opcode implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	private int id;

	@Column(name = "NAME", nullable = false, length = 50)
	private String name;

	@Column(name = "DESCRIPTION", length = 500)
	private String description;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "opcode")
	@Cache(usage = CacheConcurrencyStrategy.READ_ONLY)
	@Immutable
	private Set<OpcodeParameterLink> parameters = new HashSet<OpcodeParameterLink>(0);

	public Opcode() {
	}

	public Opcode(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Opcode(int id, String name, String description, Set<OpcodeParameterLink> parameters) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.parameters = parameters;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<OpcodeParameterLink> getParameters() {
		return this.parameters;
	}

	public void setParameters(Set<OpcodeParameterLink> parameters) {
		this.parameters = parameters;
	}

}
