package com.pourbaix.creature.editor.domain;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Immutable;

/**
 * OpcodeParameterLink generated by hbm2java
 */
@Entity
@Immutable
@Table(name = "OPCODE_PARAMETER_LINK", schema = "PUBLIC", catalog = "PUBLIC")
@Cacheable
@Cache(usage = CacheConcurrencyStrategy.READ_ONLY)
public class OpcodeParameterLink implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private Integer id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OPCODE_ID", nullable = false)
	@Immutable
	private Opcode opcode;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PARAMETER_ID", nullable = false)
	@Immutable
	private OpcodeParameter parameter;

	@Column(name = "ORDER", nullable = false)
	private byte order;

	public OpcodeParameterLink() {
	}

	public OpcodeParameterLink(Opcode opcode, OpcodeParameter parameter, byte order) {
		this.opcode = opcode;
		this.parameter = parameter;
		this.order = order;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Opcode getOpcode() {
		return this.opcode;
	}

	public void setOpcode(Opcode opcode) {
		this.opcode = opcode;
	}

	public OpcodeParameter getParameter() {
		return this.parameter;
	}

	public void setParameter(OpcodeParameter parameter) {
		this.parameter = parameter;
	}

	public byte getOrder() {
		return this.order;
	}

	public void setOrder(byte order) {
		this.order = order;
	}

}
