package com.pourbaix.creature.editor.domain;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ParameterValue generated by hbm2java
 */
@Entity
@Table(name = "PARAMETER_VALUE", schema = "PUBLIC", catalog = "PUBLIC")
public class ParameterValue implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private Integer id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARAMETER_ID", nullable = false)
	private Parameter parameter;

	@Column(name = "VALUE", length = 500)
	private String value;

	@Column(name = "DESCRIPTION", length = 1000)
	private String description;

	public ParameterValue() {
	}

	public ParameterValue(Parameter parameter) {
		this.parameter = parameter;
	}

	public ParameterValue(Parameter parameter, String value, String description) {
		this.parameter = parameter;
		this.value = value;
		this.description = description;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Parameter getParameter() {
		return this.parameter;
	}

	public void setParameter(Parameter parameter) {
		this.parameter = parameter;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
