package com.pourbaix.creature.editor.domain;

public enum ParameterEnum {
	GAME_DIRECTORY, GAME_VERSION, DEFAULT_LANGUAGE, TOBEX_ACTIVE, TARGET_ALLEGIANCE, TARGET_NEAREST_COUNT, TARGET_TYPE_COUNT, TARGET_RANDOM, PROBABILITY_ACTION_SPELL, PROBABILITY_ACTION_ITEM, CHECK_SPELL_PROTECTION, CHECK_WEAPON_PROTECTION, CHECK_ELEMENTAL_RESISTANCE, CHECK_MIND_IMMUNITY, CHECK_DEATH_IMMUNITY, CHECK_POISON_RESISTANCE, CHECK_MAGIC_DAMAGE_RESISTANCE, CHECK_MAGIC_RESISTANCE
}
