package com.pourbaix.creature.editor.domain;

import javax.persistence.Column;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.DiscriminatorType;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Parameter generated by hbm2java
 */
@Entity
@Table(name = "PARAMETER", schema = "PUBLIC", catalog = "PUBLIC")
@DiscriminatorColumn(name = "datatype", discriminatorType = DiscriminatorType.STRING)
public class Parameter implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "NAME", unique = true, nullable = false, length = 50)
	private String name;

	@Column(name = "REQUIRED", nullable = false)
	private Boolean required;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TYPE_ID")
	private ParameterType parameterType;

	@Column(name = "DATATYPE", length = 10)
	@Enumerated(value = EnumType.STRING)
	private ParameterDatatypeEnum datatype;

	@Column(name = "LABEL", length = 500)
	private String label;

	@Column(name = "DESCRIPTION", length = 1000)
	private String description;

	public Parameter() {
	}

	public Parameter(String name) {
		this.name = name;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public ParameterType getParameterType() {
		return this.parameterType;
	}

	public void setParameterType(ParameterType parameterType) {
		this.parameterType = parameterType;
	}

	public ParameterDatatypeEnum getDatatype() {
		return this.datatype;
	}

	public void setDatatype(ParameterDatatypeEnum datatype) {
		this.datatype = datatype;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getRequired() {
		return required;
	}

	public void setRequired(Boolean required) {
		this.required = required;
	}

	public String getLabel() {
		return label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

}
