package com.pourbaix.creature.editor.domain;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ParameterType generated by hbm2java
 */
@Entity
@Table(name = "PARAMETER_TYPE", schema = "PUBLIC", catalog = "PUBLIC")
public class ParameterType implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 20)
	private String id;

	@Column(name = "LABEL", length = 100)
	private String label;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parameterType")
	private Set<Parameter> parameters = new HashSet<Parameter>(0);

	public ParameterType() {
	}

	public ParameterType(String id) {
		this.id = id;
	}

	public ParameterType(String id, String label, Set<Parameter> parameters) {
		this.id = id;
		this.label = label;
		this.parameters = parameters;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public Set<Parameter> getParameters() {
		return this.parameters;
	}

	public void setParameters(Set<Parameter> parameters) {
		this.parameters = parameters;
	}

}
