package com.pourbaix.creature.editor.domain;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Spell generated by hbm2java
 */
@Entity
@Table(name = "SPELL", schema = "PUBLIC", catalog = "PUBLIC")
public class Spell implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private Integer id;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MOD_ID", nullable = false)
	private Mod mod;

	@Column(name = "RESOURCE", nullable = false, length = 8)
	private String resource;

	@Column(name = "NAME", nullable = false, length = 50)
	private String name;

	@Column(name = "IDENTIFIER", length = 50)
	private String identifier;

	@Column(name = "DESCRIPTION", length = 3000)
	private String description;

	@Column(name = "LEVEL", nullable = false)
	private int level;

	@Column(name = "TYPE", nullable = false)
	private int type;

	@Column(name = "SECONDARYTYPE", nullable = false)
	private int secondarytype;

	@Column(name = "EXCLUSIONFLAGS")
	private Integer exclusionflags;

	@Column(name = "RANGE")
	private Integer range;

	@Column(name = "SCHOOL", length = 15)
	private String school;

	@Column(name = "HURT_ALLIES", nullable = false)
	private boolean hurtAllies;

	@Column(name = "EFFECTS")
	private Integer effects;

	public Spell() {
	}

	public Spell(Mod mod, String resource, String name, int level, int type, int secondarytype, boolean hurtAllies) {
		this.mod = mod;
		this.resource = resource;
		this.name = name;
		this.level = level;
		this.type = type;
		this.secondarytype = secondarytype;
		this.hurtAllies = hurtAllies;
	}

	public Spell(Mod mod, String resource, String name, String identifier, String description, int level, int type, int secondarytype, Integer exclusionflags,
			Integer range, String school, boolean hurtAllies, Integer effects) {
		this.mod = mod;
		this.resource = resource;
		this.name = name;
		this.identifier = identifier;
		this.description = description;
		this.level = level;
		this.type = type;
		this.secondarytype = secondarytype;
		this.exclusionflags = exclusionflags;
		this.range = range;
		this.school = school;
		this.hurtAllies = hurtAllies;
		this.effects = effects;
	}

	public String toString() {
		StringBuilder sb = new StringBuilder(resource);
		sb.append(", name=").append(name);
		sb.append(", level=").append(level);
		sb.append(", identifier=").append(identifier);
		return sb.toString();
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Mod getMod() {
		return this.mod;
	}

	public void setMod(Mod mod) {
		this.mod = mod;
	}

	public String getResource() {
		return this.resource;
	}

	public void setResource(String resource) {
		this.resource = resource;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIdentifier() {
		return this.identifier;
	}

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public int getSecondarytype() {
		return this.secondarytype;
	}

	public void setSecondarytype(int secondarytype) {
		this.secondarytype = secondarytype;
	}

	public Integer getExclusionflags() {
		return this.exclusionflags;
	}

	public void setExclusionflags(Integer exclusionflags) {
		this.exclusionflags = exclusionflags;
	}

	public Integer getRange() {
		return this.range;
	}

	public void setRange(Integer range) {
		this.range = range;
	}

	public String getSchool() {
		return this.school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	public boolean isHurtAllies() {
		return this.hurtAllies;
	}

	public void setHurtAllies(boolean hurtAllies) {
		this.hurtAllies = hurtAllies;
	}

	public Integer getEffects() {
		return this.effects;
	}

	public void setEffects(Integer effects) {
		this.effects = effects;
	}

}
