package com.pourbaix.creature.editor.domain;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Trigger generated by hbm2java
 */
@Entity
@Table(name = "TRIGGER", schema = "PUBLIC", catalog = "PUBLIC")
public class Trigger implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "NAME", unique = true, nullable = false, length = 50)
	private String name;

	@Column(name = "TOBEX", nullable = false)
	private boolean tobex;

	@Column(name = "PARAMS", length = 100)
	private String params;

	@Column(name = "LABEL", length = 1500)
	private String label;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trigger")
	private Set<TriggerKeyword> triggerKeywords = new HashSet<TriggerKeyword>(0);

	public Trigger() {
	}

	public Trigger(String name, boolean tobex) {
		this.name = name;
		this.tobex = tobex;
	}

	public Trigger(String name, boolean tobex, String params, String label, Set<TriggerKeyword> triggerKeywords) {
		this.name = name;
		this.tobex = tobex;
		this.params = params;
		this.label = label;
		this.triggerKeywords = triggerKeywords;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isTobex() {
		return this.tobex;
	}

	public void setTobex(boolean tobex) {
		this.tobex = tobex;
	}

	public String getParams() {
		return this.params;
	}

	public void setParams(String params) {
		this.params = params;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public Set<TriggerKeyword> getTriggerKeywords() {
		return this.triggerKeywords;
	}

	public void setTriggerKeywords(Set<TriggerKeyword> triggerKeywords) {
		this.triggerKeywords = triggerKeywords;
	}

}
